FROM ubuntu:18.04  
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt install -y build-essential libtool \
    autotools-dev automake pkg-config bsdmainutils \
    curl git ca-certificates \
    python3 g++ gperf zip unzip \
    qtbase5-dev qttools5-dev-tools qttools5-dev \
    g++-multilib python3-setuptools
    
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

RUN mkdir -p /src

WORKDIR "/src"

ENTRYPOINT ["/entrypoint.sh"]
