FROM ubuntu:20.04  
MAINTAINER dev34253

RUN apt-get update && \
    apt-get install software-properties-common -y && \
    add-apt-repository ppa:rock-core/qt4 -y
    
RUN echo  >> /etc/apt/sources.list
    # for libssl1.0-dev need to use the old bionic apt repository
RUN echo "deb http://security.ubuntu.com/ubuntu/ bionic-security main" >> /etc/apt/sources.list
    # for libdb4.8 we need to use the old bionic apt repository
RUN echo "deb http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu bionic main" >> /etc/apt/sources.list
RUN echo  >> /etc/apt/sources.list 
# RUN wget -qO - http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu/dists/bionic/Release.gpg | apt-key add -

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C70EF1F0305A1ADB9986DBD8D46F45428842CE5E
RUN apt-get update
RUN apt-get install libdb4.8-dev libdb4.8++-dev -y

RUN export DEBIAN_FRONTEND="noninteractive" && \
 apt-get update && \
 apt-get install build-essential libtool autotools-dev automake pkg-config libssl1.0-dev libevent-dev bsdmainutils python3 -y && \
 apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev -y && \
 apt-get install software-properties-common -y && \
 apt-get install libminiupnpc-dev -y && \
 apt-get install libzmq3-dev -y && \
 apt-get install libqt4-dev libprotobuf-dev protobuf-compiler -y && \
 apt-get install libqrencode-dev -y && \
 apt-get install git -y && \
 apt-get install ca-certificates -y && \
 apt-get install unzip -y

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

WORKDIR "/src"

ENTRYPOINT ["/entrypoint.sh"]
