FROM ubuntu:16.04  
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt install -y build-essential libtool \
    autotools-dev automake pkg-config bsdmainutils \
    curl git ca-certificates \
    python3 g++ gperf zip unzip \
    qtbase5-dev qttools5-dev-tools qttools5-dev \
    g++-multilib python3-setuptools
    
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

RUN useradd -m -s /bin/bash builder && \
    echo 'builder:yacoin' | chpasswd

RUN mkdir -p /src && chown builder:builder /src

WORKDIR "/src"

USER builder

ENTRYPOINT ["/entrypoint.sh"]
