name: Docker

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile.ubuntu16.04 --tag dev32542/yacoin-build-ubuntu.16.04:0.4.9
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PWD }}" | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push image
        run: |
          docker push dev32542/yacoin-build-ubuntu.16.04:0.4.9
