name: Docker

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build image for ubuntu 20.04
        run: |
          docker build . --file Dockerfile.ubuntu.20.04 --tag dev34253/yacoin-build:ubuntu.20.04
          docker push dev34253/yacoin-build:ubuntu.20.04
      - name: Build image for ubuntu 18.04
        run: |
          docker build . --file Dockerfile.ubuntu.18.04 --tag dev34253/yacoin-build:ubuntu.18.04
          docker push dev34253/yacoin-build:ubuntu.18.04
      - name: Build image for ubuntu 16.04
        run: |
          docker build . --file Dockerfile.ubuntu.16.04 --tag dev34253/yacoin-build:ubuntu.16.04
          docker push dev34253/yacoin-build:ubuntu.16.04
